# config/routes/annotations.yaml
#controllers:
 # resource: ../../src/Controller/
  #type: annotation

#kernel:
 # resource: ../../src/Kernel.php
  #type: annotation



detailsIndex:
    path: /twigs/details
    controller: App\Controller\TwigsControllerPhpController::detailsIndex

createItemAction:
      path: /db/createitem/{name}
      controller: App\Controller\DbController::createItemAction

itemsAction:
  path: /db/items
  controller: App\Controller\DbController::itemsAction

editAction:
  path: /db/edititem/{id}
  controller: App\Controller\DbController::editAction